package com.xiyu.schedulix.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.stereotype.Controller;

import com.xiyu.schedulix.Application;
import com.xiyu.schedulix.model.SchedulixJob;
import com.xiyu.schedulix.repository.SchedulixJobRepository;


@Controller
public class SchedulixJobController {
	
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private SchedulixJobRepository sjr;

	public void addNewJOB (String WENJIAN_ID, String WENJIAN_LX, String JOB_ID,String STATUS,String DESTINATION) {

		SchedulixJob sj = new SchedulixJob();
        sj.setWENJIAN_ID(WENJIAN_ID);
        sj.setWENJIAN_LX(WENJIAN_LX);
        sj.setDESTINATION(DESTINATION);
        sj.setJOB_ID(JOB_ID);
		sj.setSTATUS(STATUS);
		sjr.save(sj);
	//	return "Saved";
	}

}